### ISSUE TITLE
NixOS Package

### ISSUE THREAD

**Issue by Bloeckchengrafik** [codelif/hyprnotify#3]
Hello,

thanks for building this, just what I need.
I'm currently in the process of [publishing a nixos package](https://github.com/NixOS/nixpkgs/pull/322883) for hyprnotify. Should I add a installation section for nixos in the readme (like the one for arch) or do you think the repology badge is enough?

Greetings from Germany and have a wonderful day!

**Comment by codelif** [comment]
sure! Thanks for the help, I wanted to add nix too, but I haven't used it I'm afraid.
