### ISSUE TITLE
More configurations

### ISSUE THREAD

**Issue by horanmustaplot** [codelif/hyprnotify#6]
Nice tool by the way :)
Please is it provides a .config folder to customize it ?

**Comment by codelif** [comment]
I presume you mean a configuration file to change the default font size and color (without hints). That's currently not available. That may be a planned feature. You can disable the sound with some cmdline options though. 


If you mean things like changing the styling, fonts, and notification position, then that's not possible with this project. That is handled by the rendering code built into `Hyprland` itself. This project does not render the notification.  

Hope this helps!

**Comment by codelif** [comment]
I don't think there is a need for a config file, it will just increase the complexity for the user, instead relevant configurations could be added as command line arguments. 

Closing this for now, feel free to comment for any suggestion.
