### ISSUE TITLE
support to body message

### ISSUE THREAD

**Issue by d3cryptofc** [codelif/hyprnotify#7]
```bash
$ notify-send --help
notify-send [OPTION…] <SUMMARY> [BODY] - create a notification
```

Currently this plugin only supports summary, ignoring the message body. I know that the Hyprland notification has no 'body' part, so I can suggest formatting both (if the 'body' message is present):

```
[SUMMARY]: BODY
```

Screenshot:
![image](https://github.com/user-attachments/assets/6b920388-3374-489b-ace3-a527fd619170)

**Comment by codelif** [comment]
Resolved by merging #8
